### ISSUE TITLE
tmr.delayus doesn't seem to have us resolution

### ISSUE THREAD

**Issue by bromagosa** [whitecatboard/LuaOS#2] opened 2016-01-14 16:23 UTC
This code in Arduino moves a servo counter-clockwise:

```
void setup() {
  pinMode(7, OUTPUT);
}

int value = 1800;

void loop() {
  digitalWrite(7, HIGH);
  delayMicroseconds(value);
  digitalWrite(7, LOW);
  delayMicroseconds(20000 - value);
}
```

While the same structure in WhiteCat Lua doesn't:

```
pio.pin.setdir(pio.OUTPUT, pio.PB_0)

function setServo(micros)
    while true do
        pio.pin.sethigh(pio.PB_0)
        tmr.delayus(micros)
        pio.pin.setlow(pio.PB_0)
        tmr.delayus(20000-micros)
    end
end

setServo(1800)
```

In Arduino, a 1200 value makes it turn clockwise, and a 1800 value makes it turn counter-clockwise.

In WhiteCat Lua, no matter what the value is, the servo always turns clockwise.

**Comment by jolivepetrus** [comment] 2016-01-15 03:24
Oops!!

Debuging with the oscilloscope tells me that in each execution Lua VM takes 1 msec, and 3 hours later I find that the problem is that Lua it's compiled with -DHARDMEMTESTS and -DHARDSTACKTESTS. This options are optional, and extremely slow in the Whitecat. Removed them in the build and signals are right in the oscilloscope. 1200 value turn clockwise and 1800 turn counter-clockwise.

Now it's work ok. Give me some more time for making some optimizations in pio Lua module. Commit of this changes will be available as soon as possible.

Thanks!

**Comment by jolivepetrus** [comment] 2016-01-15 15:13
Resolved in commit:

https://github.com/whitecatboard/LuaOS/commit/e4238497766bc87e80696ef53b2800c658f7818c

**Closed by jolivepetrus** 2016-01-15 15:13 UTC

**Comment by bromagosa** [comment] 2016-01-15 15:27
Nice! :+1:

**Comment by jolivepetrus** [comment] 2016-01-18 21:12
Thinking about this ...

Please, consider to use pwm. Your piece of code has a trivial conversion to PWM. LuaOS is a multithreaded system and it's not possible to guarantee correct signal generation using your schema. For example, if a context-switch occurs some microseconds before tmr.delayus ends next context switching occurs at the next 100 milliseconds.

For correct signal generation use PWM, so it's done by hardware.

Here you are an example code:

-- freq = 1 / T 
--
-- freq = 1 / 20 * 10^-3 = 50 hz
--
-- 1200 = duty time of 6%
-- 1800 = duty time of 8%
-- 1500 = duty time of 7.5%

direction = {
	clockwise = 0.06,
	cclockwise = 0.08,
	stop = 0.0742
}

servo1_pwm = 1
servo2_pwm = 3

pwm.setup(servo1_pwm, pwm.DEFAULT, 50, direction.stop)
pwm.start(servo1_pwm)

pwm.setup(servo2_pwm, pwm.DEFAULT, 50, direction.stop)
pwm.start(servo2_pwm)

-- Wait for some event and change direction
pwm.setduty(servo1_pwm, direction.cclockwise)

-- Wait for some event and change direction
pwm.setduty(servo2_pwm, direction.cclockwise)
